### ISSUE TITLE
FR: option to only show furigana on hover

### ISSUE THREAD

**Issue by kevindoran** [Ben-Kerman/anki-jrp#8]
A nice feature of the old addon was that you could have accent color without furigana by default; furigana could then be revealed on hover/click. 

I mostly don't want any furigana, but always want accent colors.

**Comment by Ben-Kerman** [comment]
You can get that effect by adding this to your note type style anywhere outside the addon-managed section:

```
ruby rt {
	visibility: hidden;
}

ruby:hover rt {
	visibility: visible;
}
```

And if don't want ruby text that's not from the addon to be affected, adding `[data-jrp-generate]` in front of the selectors should work, like this:

```
[data-jrp-generate] ruby rt {
	visibility: hidden;
}

[data-jrp-generate] ruby:hover rt {
	visibility: visible;
}
```
